# Default initial positions for the panda arm's ros2_control fake system
initial_positions:
  joint_a1: -1.49
  joint_a2: -1.166
  joint_a3: 0
  joint_a4: -1.936
  joint_a5: 0
  joint_a6: 1.143
  joint_a7: 3.14