# Default initial positions for the panda arm's ros2_control fake system
initial_positions:
  joint_a1: -1.57
  joint_a2: 1.57
  joint_a3: -1.57
  joint_a4: -1.57
  joint_a5: -1.57
  joint_a6: 0
  joint_a7: 0
